# Generated by Django 5.2.6 on 2025-09-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_favoritemovie_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recommendations', to='movies.movie')),
                ('source_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='movies.movie')),
            ],
            options={
                'unique_together': {('source_movie', 'recommended_movie')},
            },
        ),
    ]
