# Generated by Django 5.2.6 on 2025-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_castmember_genre_movie_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castmember',
            name='name',
        ),
        migrations.AddField(
            model_name='castmember',
            name='cast',
            field=models.CharField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
