# Generated by Django 5.2.6 on 2025-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_castmember_name_castmember_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castmember',
            old_name='cast',
            new_name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movies', to='movies.castmember'),
        ),
    ]
